# Site settings
title: Marten Schilstra | Blog
email: mail@martenschilstra.nl
description: >
  This is the blog of a software developer named Marten Schilstra
baseurl: ""
url: "http://blog.martenschilstra.nl"

# Build settings
markdown: kramdown

